[package]
name = "ssz-rs"
version = "0.8.0"
rust-version = "1.60"
authors = ["Alex Stokes <r.alex.stokes@gmail.com>"]
edition = "2021"
license = "MIT"
readme = "../README.md"
description = "ethereum's simple serialize"
repository = "https://github.com/ralexstokes/ssz-rs"
exclude = [
    "scripts",
    "tests/data",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["serde"]
serde = ["dep:serde", "dep:hex"]

[dependencies]
thiserror = "1.0.25"
bitvec = "1.0.0"
ssz-rs-derive = { path = "../ssz-rs-derive"}
sha2 = "0.9.8"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"], optional = true }
hex = {version = "0.4.3", optional = true }
num-bigint = "0.4.3"
fields-iter = "0.0.3"
as-any = "0.3.0"
itertools = "0.10.5"

[dev-dependencies]
hex-literal = "0.3.3"
snap = "1.0"
project-root = "0.2.2"
serde_json = "1.0.81"
